'use client';
import {ArrowRight,Bell,CalendarDays,Wallet} from 'lucide-react';
import {nextMoneyEvents,type MoneyEvent} from '@/services/notifications';
import {money,summarize} from '@/services/finance';
import type {FinanceState} from '@/types/finance';
const when=(e:MoneyEvent)=>e.days<0?`${Math.abs(e.days)} day${e.days===-1?'':'s'} overdue`:e.days===0?(e.kind==='bill'?'Due today':'Expected today'):e.days===1?'Tomorrow':`In ${e.days} days`;
const dateLabel=(date:string)=>new Date(date+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'});
export default function NextUp({state,data,open}:{state:FinanceState;data:ReturnType<typeof summarize>;open:(type:string,id?:string)=>void}){
 const events=nextMoneyEvents(state,data.date),next=events[0];
 const action=(event:MoneyEvent)=>event.kind==='payday'?open('paydays'):open(event.days<=0?'payBill':'editBill',event.days<=0?`${event.recordId}|${event.date}`:event.recordId);
 return <section className="next-up-card"><div className="flex-between"><span className="eyebrow">{next?.days<0?'NEEDS YOUR ATTENTION':'WHAT’S COMING NEXT'}</span><CalendarDays size={20}/></div>{next?<><h2 className="next-up-title">{next.kind==='payday'?'Payday':next.name}</h2><div className="next-up-countdown">{next.days===0?'Today':next.days===1?'Tomorrow':<>{Math.abs(next.days)}<span>{next.days<0?'days overdue':'days to go'}</span></>}</div><p className="next-up-amount">{next.kind==='payday'?'Estimated +':''}{money(next.amount,2)}<span> · {dateLabel(next.date)}</span></p><p className="next-up-hint">{next.kind==='payday'?'Your expected income. Confirm the amount when it arrives.':next.days<0?'Still marked unpaid. Record it if you’ve already paid.':'Your next tracked payment. A little time to prepare.'}</p><button className="next-up-action" onClick={()=>action(next)}>{next.kind==='payday'?'View payday':next.days<=0?'Record payment':'View bill'}<ArrowRight size={17}/></button>{events.length>1&&<div className="next-up-list"><p className="eyebrow">ALSO ON YOUR CALENDAR</p>{events.slice(1).map(e=><button key={e.id} onClick={()=>action(e)}><span className="next-up-event-icon">{e.kind==='payday'?<Wallet size={18}/>:<CalendarDays size={18}/>}</span><span className="next-up-event-copy"><b>{e.name}</b><small>{when(e)} · {dateLabel(e.date)}</small></span><strong>{e.kind==='payday'?'~+':''}{money(e.amount)}</strong></button>)}</div>}</>:<><h2 className="next-up-title">A clear calendar.</h2><p>No unpaid bills or expected income in the next year. Add a payday or bill to see what’s coming.</p><div className="next-up-empty"><button className="next-up-action" onClick={()=>open('paydays')}>Add payday<ArrowRight size={17}/></button><button className="next-up-action" onClick={()=>open('bill')}>Add bill<ArrowRight size={17}/></button></div></>}<div className="next-up-tools"><button onClick={()=>open('reminders')}><Bell size={16}/>Payday & bill reminders</button><details><summary>View cash-flow forecast</summary><div className="next-up-forecast"><strong>{data.runway.days}{data.runway.capped?'+':''} days of projected runway</strong><p>{data.runway.capped?'No cash-buffer shortfall was found in the next 180 days. This is the forecast limit, not a countdown to your next event.':'The forecast reaches your protected cash buffer in this many days.'}</p><p>Includes estimated income and recurring commitments. Current cash: {money(data.balance)}. Protected buffer: {money(state.protectedMinimum)}. Planned spending: {money(data.daily,2)}/day.</p></div></details></div></section>;
}
