'use client';
import {useEffect,useState} from 'react';
import useEmblaCarousel from 'embla-carousel-react';
import {ArrowRight,Bell,CalendarDays,Wallet,Flag,Sparkles,Pause,Play,ShieldCheck} from 'lucide-react';
import {money,summarize} from '@/services/finance';
import {nextMoneyEvents} from '@/services/notifications';
import type {FinanceState} from '@/types/finance';
const dateLabel=(date:string)=>new Date(date+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'});
const when=(days:number)=>days<0?`${Math.abs(days)} days overdue`:days===0?'Today':days===1?'Tomorrow':`In ${days} days`;
export default function Overview({state,data,open,navigate}:{state:FinanceState;data:ReturnType<typeof summarize>;open:(type:string,id?:string)=>void;navigate:(tab:string)=>void}){
 const goal=state.goals[0],percent=goal?Math.min(100,Math.round(goal.saved/Math.max(1,goal.target)*100)):0;
 const bills=data.bills.filter(b=>b.days>=0&&b.days<7),total=bills.reduce((sum,b)=>sum+b.amount,0);
 const events=nextMoneyEvents(state,data.date);
 if(data.payday&&!events.some(e=>e.kind==='payday'))events.push({id:'next-payday',recordId:'next-payday',kind:'payday',name:'Payday',date:data.payday.date,days:data.payday.days,amount:data.payday.amount});
 const slides=events.map(e=>({id:e.id,tone:e.kind==='payday'?'lavender':'blush',icon:e.kind==='payday'?'💸':'🗓',title:e.kind==='payday'?'Payday is on the way':e.name,amount:`${e.kind==='payday'?'~+':''}${money(e.amount)}`,detail:`${e.kind==='payday'?'Expected':'Due'} ${dateLabel(e.date)} · ${when(e.days)}`,hint:e.kind==='payday'?'An estimate today. Confirm it when it arrives.':e.days<0?'Still marked unpaid. Already paid? Update it here.':'A little time to prepare for your next payment.',action:e.kind==='payday'?'Plan my paycheck':'View payment',onClick:()=>e.kind==='payday'?open('planner'):open(e.days<=0?'payBill':'editBill',e.days<=0?`${e.recordId}|${e.date}`:e.recordId)}));
 if(goal)slides.push({id:goal.id,tone:'peach',icon:'🎯',title:goal.name,amount:`${percent}% complete`,detail:`${money(Math.max(0,goal.target-goal.saved))} left to your goal`,hint:percent===100?'You reached your target. Take a moment to celebrate.':'Little by little, you’re building something good.',action:'Add money',onClick:()=>open('contribute',goal.id)});
 if(!slides.length)slides.push({id:'empty',tone:'sage',icon:'🌱',title:'A little plan starts here',amount:'Make room for next',detail:'Add a bill, payday, or savings goal.',hint:'Your next money moments will appear here.',action:'Add a payday',onClick:()=>open('paydays')});
 const [ref,api]=useEmblaCarousel({loop:true});const [active,setActive]=useState(0),[paused,setPaused]=useState(false),[reduced,setReduced]=useState(true);
 useEffect(()=>{const query=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(query.matches);update();query.addEventListener('change',update);return()=>query.removeEventListener('change',update);},[]);
 useEffect(()=>{if(!api)return;const select=()=>setActive(api.selectedScrollSnap());const stop=()=>setPaused(true);api.on('select',select);api.on('reInit',select);api.on('pointerDown',stop);return()=>{api.off('select',select);api.off('reInit',select);api.off('pointerDown',stop);};},[api]);
 useEffect(()=>{if(!api||paused||reduced||slides.length<2)return;const timer=setInterval(()=>{if(!document.hidden)api.scrollNext();},6000);return()=>clearInterval(timer);},[api,paused,reduced,slides.length]);
 return <div className="gift-overview">
 <div className="gift-summaries" aria-label="Your money at a glance">
 <button className="gift-mini sage" onClick={()=>open('purchase')}><span><Wallet size={17}/>Available to spend</span><strong key={data.free}>{money(data.free)}</strong><small>After commitments · until payday</small></button>
 <button className="gift-mini blush" onClick={()=>navigate('Bills')}><span><CalendarDays size={17}/>Bills coming</span><strong key={total}>{bills.length} · {money(total)}</strong><small>Next 7 days</small></button>
 <button className="gift-mini lavender" onClick={()=>open('paydays')}><span><Wallet size={17}/>Next payday</span><strong>{data.payday?when(data.payday.days):'Add payday'}</strong><small>{data.payday?`${dateLabel(data.payday.date)} · estimated ${money(data.payday.amount)}`:'Build your income plan'}</small></button>
 <button className="gift-mini peach" onClick={()=>goal?open('goal',goal.id):open('goal')}><span><Flag size={17}/>Savings goal</span><strong key={percent}>{goal?`${percent}%`:'Start small'}</strong><small>{goal?goal.name:'Give a wish a little room'}</small></button>
 </div>
 <div className="gift-status"><ShieldCheck size={16}/><span>{data.free>0?`${money(data.free)} available after planned commitments`:'Let’s review your upcoming commitments'}</span></div>
 <div className="gift-middle"><section className="gift-carousel" aria-roledescription="carousel" aria-label="Your next money moments" onMouseEnter={()=>setPaused(true)} onFocusCapture={()=>setPaused(true)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();setPaused(true);e.key==='ArrowRight'?api?.scrollNext():api?.scrollPrev();}}}>
 <div className="gift-viewport" ref={ref}><div className="gift-slides">{slides.map((s,i)=><article className={`gift-slide ${s.tone}`} key={s.id} role="group" aria-roledescription="slide" aria-label={`${i+1} of ${slides.length}`} inert={i!==active}><div className="gift-slide-copy"><span className="eyebrow">YOUR NEXT MONEY MOMENT</span><h2>{s.title}</h2><strong>{s.amount}</strong><p>{s.detail}</p><small>{s.hint}</small><button onClick={s.onClick}>{s.action}<ArrowRight size={16}/></button></div><span className="gift-slide-art" aria-hidden="true">{s.icon}</span></article>)}</div></div>
 <div className="gift-carousel-controls"><div>{slides.map((s,i)=><button key={s.id} className={active===i?'selected':''} aria-label={`Show ${s.title}`} aria-current={active===i?'true':undefined} onClick={()=>{setPaused(true);api?.scrollTo(i);}}/>)}</div>{!reduced&&slides.length>1&&<button className="gift-motion" onClick={()=>setPaused(!paused)} aria-label={paused?'Resume automatic slides':'Pause automatic slides'}>{paused?<Play size={14}/>:<Pause size={14}/>}</button>}</div></section>
 <section className="gift-week"><div className="flex-between"><h2>This week</h2><CalendarDays size={17}/></div>{bills.length?bills.slice(0,3).map(b=><button className="gift-calendar-row" key={b.id+b.due} onClick={()=>open(b.days===0?'payBill':'editBill',b.days===0?`${b.id}|${b.due}`:b.id)}><span>{dateLabel(b.due)}</span><b>{b.name}</b><strong>{money(b.amount)}</strong></button>):<p className="subtle">No tracked bills due in the next seven days.</p>}<button className="gift-link" onClick={()=>navigate('Bills')}>View all bills <ArrowRight size={15}/></button></section></div>
 <div className="gift-lower"><section className="gift-detail peach"><span className="eyebrow">🎯 A LITTLE CLOSER</span><h2>{goal?.name??'Something to look forward to'}</h2>{goal?<><div className="flex-between"><span>{money(goal.saved)} of {money(goal.target)}</span><b>{percent}%</b></div><progress value={percent} max={100} aria-label={`${goal.name} progress`}/><button className="gift-link" onClick={()=>open('contribute',goal.id)}>{percent>=100?'Keep growing':'Add money'}<ArrowRight size={15}/></button></>:<><p>Turn something you want into a savings goal.</p><button className="gift-link" onClick={()=>open('goal')}>Create a goal <ArrowRight size={15}/></button></>}</section>
 <section className="gift-detail butter"><span className="eyebrow"><Sparkles size={15}/> GIFT INSIGHT</span><h2>{data.safe.remaining>0?'A little room for today':'Time for a little check-in'}</h2><p>{data.safe.remaining>0?`${money(data.safe.remaining)} remains in today’s spending allowance. Small choices can help it go further.`:'You’ve reached today’s spending allowance. Review your plan before your next purchase.'}</p><button className="gift-link" onClick={()=>open('review')}>Your weekly review <ArrowRight size={15}/></button></section></div>
 <div className="gift-tools"><button onClick={()=>open('reminders')}><Bell size={16}/>Payday & bill reminders</button><button onClick={()=>open('account')}>Manage accounts</button><button onClick={()=>open('transaction')}>Add spending <ArrowRight size={15}/></button></div>
 <details className="gift-forecast"><summary>Cash-flow forecast & daily allowance</summary><p>{data.runway.days}{data.runway.capped?'+':''} days of projected runway · {money(data.safe.remaining)} left today.</p><p className="subtle">{data.runway.capped?'Your forecast stays above your protected buffer for the next 180 days. ':''}Based on estimated income and planned spending. Future deposits aren’t added to your balance until confirmed.</p></details>
 </div>;
}
