'use client';
import {useState} from 'react';
import {financeSchema} from '@/lib/validation';
import type {FinanceState} from '@/types/finance';
export default function ImportBudget(){
 const [budget,setBudget]=useState<FinanceState|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(file?:File){setError('');setBudget(null);if(!file)return;try{if(file.size>3000000)throw new Error('This file is too large.');const parsed=financeSchema.safeParse(JSON.parse(await file.text()));if(!parsed.success)throw new Error('Choose an exported Gift or Carry budget JSON file.');setBudget(parsed.data);}catch(e){setError(e instanceof Error?e.message:'Could not read this file.');}}
 async function save(){if(!budget)return;setBusy(true);setError('');try{const response=await fetch('/api/finance',{cache:'no-store'});const current=await response.json() as {revision:number;error:string};if(!response.ok)throw new Error(current.error);const saved=await fetch('/api/finance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:budget,revision:current.revision})});const result=await saved.json() as {error:string};if(!saved.ok)throw new Error(result.error);window.location.assign('/');}catch(e){setError(e instanceof Error?e.message:'Import failed. Please retry.');setBusy(false);}}
 return <main className="startup"><section style={{maxWidth:480,padding:24}}><a className="brand" href="/">Gift</a><h1>Bring your budget with you</h1><p>Choose the JSON file from Settings → Export my data in your existing app. Importing replaces the budget in this signed-in account. Your original app stays unchanged.</p><input aria-label="Exported budget file" type="file" accept="application/json,.json" disabled={busy} onChange={e=>void load(e.target.files?.[0])}/>{budget&&<><p>{budget.accounts.length} accounts · {budget.transactions.length} transactions · {budget.bills.length} bills · {budget.goals.length} goals</p><button className="primary" disabled={busy} onClick={()=>void save()}>{busy?'Importing…':'Replace this account’s budget with this file'}</button></>}{error&&<p role="alert">{error}</p>}<p><a href="/">Back to your budget</a></p></section></main>;
}
