'use client';
import {useState} from 'react';
import type {FinanceState} from '@/types/finance';
import {money,today} from '@/services/finance';
import {preparePhoto,uploadPhoto} from '@/lib/lifestyle/photos';
export default function Memories({state,goalId,save}:{state:FinanceState;goalId:string;save:(s:FinanceState)=>Promise<boolean>}){
 const [city,setCity]=useState(''),[country,setCountry]=useState(''),[date,setDate]=useState(today(state.timezone)),[note,setNote]=useState(''),[spent,setSpent]=useState(''),[file,setFile]=useState<File>(),[busy,setBusy]=useState(false),[error,setError]=useState('');const entries=(state.memories??[]).filter(m=>m.goalId===goalId);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');let photoId:string|undefined;try{const cents=Math.round(Number(spent||0)*100);if(!Number.isSafeInteger(cents)||cents<0)throw new Error('Enter a valid amount.');if(file)photoId=await uploadPhoto(await preparePhoto(file));if(!await save({...state,memories:[...(state.memories??[]),{id:crypto.randomUUID(),goalId,city,country,date,note,photoId,spent:cents}]}))throw new Error('Could not save this memory.');setCity('');setCountry('');setNote('');setSpent('');setFile(undefined);}catch(e){if(photoId)await fetch('/api/media?id='+photoId,{method:'DELETE'});setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="travel-memories"><summary>Travel journal & memories · {entries.length}</summary><p className="subtle">Remember where you went and what it cost. Journal amounts are notes only—record purchases in Spending to update your balance.</p><form onSubmit={submit}><div className="form-grid"><label className="field">City or town<input className="carry-input" required maxLength={100} value={city} onChange={e=>setCity(e.target.value)}/></label><label className="field">Country<input className="carry-input" required maxLength={100} value={country} onChange={e=>setCountry(e.target.value)}/></label></div><div className="form-grid"><label className="field">Date<input className="carry-input" type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field">Cost to remember ($)<input className="carry-input" type="number" min="0" step="0.01" value={spent} onChange={e=>setSpent(e.target.value)}/></label></div><label className="field">A moment to remember<textarea className="carry-input" maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><label className="field">Photo · optional<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0])}/></label><p className="subtle">Private to your account. Location is entered by you; Gift doesn’t track where you are.</p><button className="secondary" disabled={busy}>{busy?'Saving…':'Save memory'}</button>{error&&<p role="alert">{error}</p>}</form>{entries.map(m=><article className="memory-card" key={m.id}>{m.photoId&&<img alt={m.city+', '+m.country} loading="lazy" src={'/api/media?id='+m.photoId}/>}<h3>{m.city}, {m.country}</h3><p>{m.date} · {money(m.spent,2)} noted</p><p>{m.note}</p><button className="text-action" disabled={busy} onClick={async()=>{if(!window.confirm('Delete this memory and its photo?'))return;setBusy(true);if(await save({...state,memories:state.memories!.filter(x=>x.id!==m.id)})&&m.photoId)await fetch('/api/media?id='+m.photoId,{method:'DELETE'});setBusy(false);}}>Delete memory</button></article>)}</details>;
}
