import { LegalPage } from "@/components/legal/page-shell";

export default function FinancialDisclaimerPage() {
  return (
    <LegalPage
      title="Financial Disclaimer"
      summary="Gift is a budgeting and planning tool. This page explains the limits of its estimates, reminders, and Advisor responses."
    >
      <section>
        <h2>Planning information, not professional advice</h2>
        <p>
          Gift provides educational budgeting information based on figures and
          dates entered by the user. Gift does not provide financial,
          investment, tax, legal, accounting, credit, insurance, or debt-relief
          advice and does not act as a fiduciary. Consult a qualified
          professional for advice about your circumstances.
        </p>
      </section>
      <section>
        <h2>Estimates can change</h2>
        <p>
          Runway, safe-to-spend, cash-flow, goal dates, budget pace, and
          purchase scenarios are projections. They depend on the accuracy and
          completeness of your entries and assumptions about future income,
          spending, bills, and timing. Actual results can differ significantly.
        </p>
      </section>
      <section>
        <h2>No verification or money movement</h2>
        <p>
          Gift does not verify bank balances, deposits, charges, prices, or
          payments. Expected income is not added until you confirm it. Recording
          a payment does not pay a bill. Gift does not monitor provider accounts
          or cancel subscriptions on your behalf.
        </p>
      </section>
      <section>
        <h2>Reminders are a convenience</h2>
        <p>
          In-app and email reminders may be delayed, unavailable, or based on an
          outdated date. You remain responsible for reviewing statements,
          maintaining sufficient funds, paying obligations on time, and
          confirming transactions with the relevant institution or provider.
        </p>
      </section>
      <section>
        <h2>AI-generated responses</h2>
        <p>
          Advisor responses may be generated by an AI model. AI can
          misunderstand a question, overlook context, or produce incorrect
          information. Treat its response as a starting point, verify the
          figures displayed in Gift, and do not rely on it for high-stakes
          decisions.
        </p>
      </section>
      <section>
        <h2>Contact</h2>
        <p>
          Questions about this disclaimer may be sent to{" "}
          <a href="mailto:support@budgetwithgift.com">
            support@budgetwithgift.com
          </a>
          .
        </p>
      </section>
    </LegalPage>
  );
}
