import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState} from '../services/finance/sample';
import {today,addDays,forecastBalance,occurs} from '../services/finance/index';
import {makeDraft,completeSetup,validateStep} from '../services/onboarding/model';
import {dueReminders,remindersFor,confirmPaycheck,nextMoneyEvents} from '../services/notifications/index';
import {reminderEmail,sendReminderEmail} from '../services/notifications/email';
import {financeSchema} from '../lib/validation';
const date='2026-09-24';
function readyDraft(){const s=emptyState(date);s.timezone='America/Los_Angeles';const d=makeDraft(s);d.name='Taylor';d.cash='2075';d.housing='rent';d.income=[{id:'pay',name:'Main job',employer:'Example employer',amount:'2075',date:'2026-09-26',frequency:'biweekly',payDays:[1,15]}];d.bills=[{id:'rent',name:'Rent',amount:'1240',date:'2026-10-01',frequency:'monthly',subscription:false,selected:true}];d.categories.forEach((c,i)=>c.budget=['320','100','300'][i]);d.goals=[{id:'trip',name:'Vacation',target:'5000',saved:'0',contribution:'300',date:'2026-10-02',targetDate:'2027-09-24',icon:'✈'}];return {s,d};}
test('one setup completion creates a coherent plan without crediting expected income',()=>{const {s,d}=readyDraft();const result=completeSetup(s,d,date);assert.equal(result.accounts[0].balance,207500);assert.equal(result.income[0].amount,207500);assert.equal(result.bills[0].amount,124000);assert.equal(result.goals[0].contribution,30000);assert.equal(result.setupVersion,2);assert.equal(result.timezone,'America/Los_Angeles');assert.ok(financeSchema.safeParse(result).success);});
test('setup validation permits no income but rejects incomplete selected bills and malformed money',()=>{const {s,d}=readyDraft();d.income=[];assert.doesNotThrow(()=>completeSetup(s,d,date));d.cash='1.005';assert.throws(()=>validateStep(d,0,date));d.cash='2075';d.bills[0].date='';assert.throws(()=>validateStep(d,3,date));});
test('unselected optional bills do not become obligations',()=>{const {s,d}=readyDraft();d.bills.push({id:'car',name:'Car',amount:'',date:'',frequency:'monthly',subscription:false,selected:false});assert.equal(completeSetup(s,d,date).bills.length,1);});
test('editing guided setup preserves transactions, receipts, and additional accounts',()=>{const {s,d}=readyDraft();s.accounts=[{id:'a',name:'Checking',balance:100},{id:'b',name:'Other',balance:50000}];s.onboarded=true;s.transactions=[{id:'t',merchant:'Cafe',amount:500,date,categoryId:'groceries',excluded:false,recurring:false,note:''}];const next=completeSetup(s,d,date);assert.equal(next.accounts[1].balance,50000);assert.equal(next.transactions.length,1);});
test('two-day payday reminder uses estimates and upcoming bill totals',()=>{const {s,d}=readyDraft();const next=completeSetup(s,d,date);const reminders=dueReminders(next,date);assert.equal(reminders.length,1);assert.equal(reminders[0].kind,'payday');assert.match(reminders[0].title,/2 days/);assert.match(reminders[0].body,/estimated|estimate/i);assert.match(reminders[0].body,/1,240/);assert.equal(dueReminders(next,'2026-09-25').length,0);next.reminders!.paydayEnabled=false;assert.equal(dueReminders(next,date).length,0);});
test('bill reminder respects lead time and paid/paused states',()=>{const {s,d}=readyDraft();const next=completeSetup(s,d,date);assert.ok(dueReminders(next,'2026-09-28').some(r=>r.kind==='bill'));next.bills[0].paidDates=['2026-10-01'];assert.ok(!remindersFor(next,date).some(r=>r.recordId==='rent'&&r.due==='2026-10-01'));next.bills[0].paused=true;assert.ok(!remindersFor(next,date).some(r=>r.recordId==='rent'));});
test('actual paycheck receipt changes cash once and removes that forecast occurrence',()=>{const {s,d}=readyDraft();const original=completeSetup(s,d,date);const before=JSON.stringify(original);const recorded=confirmPaycheck(original,'pay','2026-09-26',198000,original.accounts[0].id,today('America/Los_Angeles'));assert.equal(recorded.accounts[0].balance,405500);assert.equal(forecastBalance(recorded,'2026-09-26',1)[0].income,0);assert.throws(()=>confirmPaycheck(recorded,'pay','2026-09-26',198000,original.accounts[0].id));assert.equal(JSON.stringify(original),before);assert.equal(recorded.income[0].amount,207500);});
test('twice-monthly custom pay dates clamp the last day of February',()=>{const schedule={date:'2026-01-15',frequency:'semimonthly' as const,payDays:[15,31]};assert.ok(occurs(schedule,'2026-02-28'));assert.ok(occurs(schedule,'2026-03-31'));assert.ok(!occurs(schedule,'2026-03-01'));});
test('email adapter uses the fixed verified recipient and an idempotency key',async()=>{const {s,d}=readyDraft();const reminder=dueReminders(completeSetup(s,d,date),date)[0];const payload=reminderEmail(reminder,'test@example.com','Gift <reminders@example.com>','https://gift.example');assert.match(payload.text,/not verified/);let called=false;const result=await sendReminderEmail(payload,'fake-key','stable-key',async(url,init)=>{called=true;assert.equal(url,'https://api.resend.com/emails');assert.equal((init?.headers as Record<string,string>)['Idempotency-Key'],'stable-key');assert.deepEqual(JSON.parse(init!.body as string).to,['test@example.com']);return new Response(JSON.stringify({id:'test-message'}),{status:200});});assert.ok(called);assert.equal(result,'test-message');});

test('home events prioritize overdue bills, then nearest date, with bills first on ties',()=>{const {s,d}=readyDraft();const next=completeSetup(s,d,date);assert.equal(nextMoneyEvents(next,date)[0].kind,'payday');next.bills[0].date='2026-09-26';assert.equal(nextMoneyEvents(next,date)[0].kind,'bill');next.bills[0].date='2026-09-23';assert.equal(nextMoneyEvents(next,date)[0].days,-1);next.bills[0].paidDates=['2026-09-23'];assert.equal(nextMoneyEvents(next,date)[0].kind,'payday');next.income[0].receivedDates=['2026-09-26'];assert.notEqual(nextMoneyEvents(next,date)[0].date,'2026-09-26');});
test('event countdown changes with local date and empty calendars stay empty',()=>{const {s,d}=readyDraft();const next=completeSetup(s,d,date);assert.equal(nextMoneyEvents(next,'2026-09-25')[0].days,1);assert.equal(nextMoneyEvents(next,'2026-09-26')[0].days,0);next.income=[];next.bills[0].paused=true;assert.deepEqual(nextMoneyEvents(next,date),[]);});
