import {db} from '@/lib/store';
import {emailConfig} from '@/lib/email-config';
import {dueReminders} from '@/services/notifications';
import {reminderEmail,sendReminderEmail,type EmailPayload} from '@/services/notifications/email';
import type {FinanceState} from '@/types/finance';
export const dynamic='force-dynamic';
async function authorized(header:string|null,secret:string){const a=new TextEncoder().encode(header??''),b=new TextEncoder().encode('Bearer '+secret);const [ah,bh]=await Promise.all([crypto.subtle.digest('SHA-256',a),crypto.subtle.digest('SHA-256',b)]);let diff=0;const x=new Uint8Array(ah),y=new Uint8Array(bh);for(let i=0;i<x.length;i++)diff|=x[i]^y[i];return diff===0;}
export async function POST(request:Request){const config=emailConfig();if(!config.secret||!await authorized(request.headers.get('authorization'),config.secret))return Response.json({error:'Unauthorized'},{status:401});if(!config.key||!config.from)return Response.json({error:'Email sender is not configured.'},{status:503});let accepted=0,failed=0;try{let cursor='';while(true){const rows=await db().prepare('SELECT p.user_id,p.data,r.email FROM financial_profiles p JOIN email_recipients r ON r.user_id=p.user_id WHERE r.enabled=1 AND p.user_id>? ORDER BY p.user_id LIMIT 100').bind(cursor).all<{user_id:string;data:string;email:string}>();if(!rows.results.length)break;for(const row of rows.results){cursor=row.user_id;const state:FinanceState=JSON.parse(row.data);if(!state.onboarded||!state.reminders?.emailEnabled)continue;const hour=Number(new Intl.DateTimeFormat('en-US',{timeZone:state.timezone??'UTC',hour:'2-digit',hourCycle:'h23'}).format(new Date()));if(hour<state.reminders.sendHour)continue;for(const reminder of dueReminders(state)){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(`${row.user_id}:${reminder.id}`));const id=Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');const existing=await db().prepare('SELECT status,created_at,payload FROM email_deliveries WHERE id=?').bind(id).first<{status:string;created_at:string;payload:string}>();const age=existing?Date.now()-Date.parse(existing.created_at):0;if(existing&&(existing.status==='sent'||existing.status==='failed'||age>=23*3600000||existing.status==='sending'&&age<10*60000))continue;const payload:EmailPayload=existing?JSON.parse(existing.payload):reminderEmail(reminder,row.email,config.from,config.origin);const claim=existing?await db().prepare("UPDATE email_deliveries SET status='sending' WHERE id=? AND status=?").bind(id,existing.status).run():await db().prepare("INSERT INTO email_deliveries (id,user_id,status,created_at,payload) VALUES (?,?,'sending',?,?) ON CONFLICT(id) DO NOTHING").bind(id,row.user_id,new Date().toISOString(),JSON.stringify(payload)).run();if(!claim.meta.changes)continue;try{const current=await db().prepare('SELECT enabled FROM email_recipients WHERE user_id=?').bind(row.user_id).first<{enabled:number}>();if(!current?.enabled){await db().prepare("UPDATE email_deliveries SET status='failed',payload='{}' WHERE id=?").bind(id).run();continue;}const providerId=await sendReminderEmail(payload,config.key,id);await db().prepare("UPDATE email_deliveries SET status='sent',provider_id=?,payload='{}' WHERE id=?").bind(providerId,id).run();accepted++;}catch(e){failed++;await db().prepare('UPDATE email_deliveries SET status=? WHERE id=?').bind((e as Error&{retryable?:boolean}).retryable===false?'failed':'retry',id).run();}}}if(rows.results.length<100)break;}
 await db().prepare("INSERT INTO audit_events (id,user_id,action,created_at) VALUES ('reminder-job-heartbeat','system','email_reminder_dispatch',?) ON CONFLICT(id) DO UPDATE SET created_at=excluded.created_at").bind(new Date().toISOString()).run();return Response.json({accepted,failed},{status:failed?503:200});}catch{return Response.json({error:'Reminder dispatch failed. Retry with the same job configuration.'},{status:503});}}
