'use client';
import {useEffect,useState,useRef} from 'react';
import {ArrowRight,ArrowLeft,Plus,Check,BriefcaseBusiness,House,Wallet,CalendarDays,Flag,Bell,ClipboardCheck,Trash2,Smile} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Field,Choice,uid} from '@/components/carry/shared';
import {addDays,monthDate,today,money,summarize} from '@/services/finance';
import {billGroups,makeDraft,validateStep,completeSetup,type SetupDraft,type SetupBill,type SetupIncome,parseAmount} from '@/services/onboarding/model';
import {ReminderFields,useDeliveryInfo} from '@/features/reminders/settings';
import type {FinanceState,Frequency} from '@/types/finance';
const steps=[{title:'Start with where you are.',label:'Your starting point',icon:Wallet,description:'A few real numbers will make this your plan.'},{title:'Tell us how you get paid.',label:'Work & income',icon:BriefcaseBusiness,description:'Use the amount that reaches your account after tax. An estimate is completely fine.'},{title:'Let’s start with home.',label:'Housing',icon:House,description:'Tell us about your share of the regular housing payment.'},{title:'What else needs covering?',label:'Regular bills',icon:CalendarDays,description:'Choose only what applies. We’ll turn these into tracked bills for you.'},{title:'Everyday life, and what’s next.',label:'Spending & savings',icon:Flag,description:'Set comfortable spending limits and, if you like, a first savings goal.'},{title:'A little heads-up helps.',label:'Reminders',icon:Bell,description:'Choose when Carry should remind you about expected pay and upcoming bills.'},{title:'Your plan, all in one place.',label:'Review & finish',icon:ClipboardCheck,description:'Check these estimates before we create your budget. You can change them later.'}];
const frequencies=[{value:'weekly',label:'Every week'},{value:'biweekly',label:'Every two weeks'},{value:'semimonthly',label:'Twice a month'},{value:'monthly',label:'Monthly'},{value:'once',label:'Irregular / one expected payment'}];
const billFrequencies=[...frequencies.filter(x=>x.value!=='semimonthly'),{value:'yearly',label:'Yearly'}];
export function IncomeFields({income,onChange,onRemove}:{income:SetupIncome;onChange:(i:SetupIncome)=>void;onRemove?:()=>void}){return <section className="setup-detail"><div className="flex-between"><h3>{income.name||'Income source'}</h3>{onRemove&&<button type="button" className="text-action" onClick={onRemove} aria-label={`Remove ${income.name||'income source'}`}><Trash2 size={16}/></button>}</div><Field label="Income source name" value={income.name} onChange={name=>onChange({...income,name})}/><Field label="Employer or source · optional" required={false} value={income.employer} onChange={employer=>onChange({...income,employer})}/><Field label="Estimated take-home amount ($)" value={income.amount} onChange={amount=>onChange({...income,amount})} type="number" min={0} step="0.01"/><Choice label="How often do you get paid?" value={income.frequency} onChange={frequency=>onChange({...income,frequency:frequency as Frequency})} options={frequencies}/>{income.frequency==='semimonthly'&&<div className="form-grid">{[0,1].map(index=><Choice key={index} label={index===0?'First pay day':'Second pay day'} value={String(income.payDays[index])} onChange={v=>onChange({...income,payDays:income.payDays.map((x,j)=>j===index?Number(v):x)})} options={Array.from({length:31},(_,i)=>({value:String(i+1),label:i===30?'Last day of month':String(i+1)}))}/>)}</div>}<Field label="Next expected payday" type="date" value={income.date} onChange={date=>onChange({...income,date})}/><p className="subtle">Already received this paycheck? Include it in your starting balance and enter the next expected date here. Carry won’t contact your employer.</p></section>}
function BillFields({bill,onChange}:{bill:SetupBill;onChange:(b:SetupBill)=>void}){return <div className="setup-detail bill-detail"><Field label="Bill name" value={bill.name} onChange={name=>onChange({...bill,name})}/><div className="form-grid"><Field label="Your payment ($)" type="number" min={0} step="0.01" value={bill.amount} onChange={amount=>onChange({...bill,amount})}/><Field label="Next unpaid due date" type="date" value={bill.date} onChange={date=>onChange({...bill,date})}/></div><Choice label="How often is it due?" value={bill.frequency} onChange={frequency=>onChange({...bill,frequency:frequency as Frequency})} options={billFrequencies}/><label className="toggle-row"><Checkbox checked={bill.subscription} onCheckedChange={v=>onChange({...bill,subscription:v===true})}/>This is a subscription</label></div>}
export default function Onboarding({initialState,profileRevision,onComplete,onCancel,embedded=false}:{initialState:FinanceState;profileRevision:number;onComplete:(result:{state:FinanceState;revision:number})=>void;onCancel?:()=>void;embedded?:boolean}){
 const [draft,setDraft]=useState<SetupDraft>(()=>makeDraft(initialState)),[draftRevision,setDraftRevision]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(''),[loadFailed,setLoadFailed]=useState(false);
 const delivery=useDeliveryInfo(),heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{let alive=true;fetch('/api/setup').then(async r=>{const value=await r.json() as {draft:SetupDraft|null;revision:number;error?:string};if(!r.ok)throw new Error(value.error);if(alive){if(value.draft)setDraft(value.draft);setDraftRevision(value.revision);setLoading(false)}}).catch(()=>{if(alive){setError('Could not load saved progress. Reload before entering details.');setLoadFailed(true);setLoading(false)}});return()=>{alive=false}},[]);
 const step=draft.step,details=steps[step],date=today(draft.timezone);
 const update=(patch:Partial<SetupDraft>)=>{setDraft(d=>({...d,...patch}));setError('');setSaved('')};
 const jump=(step:number)=>update({step,slide:0});
 const editBill=(b:SetupBill)=>update({bills:draft.bills.map(x=>x.id===b.id?b:x)});
 const editIncome=(i:SetupIncome)=>update({income:draft.income.map(x=>x.id===i.id?i:x)});
 function chooseBill(id:string,name:string,selected:boolean){const previous=draft.bills.find(x=>x.id===id);update({bills:previous?draft.bills.map(x=>x.id===id?{...x,selected}:x):[...draft.bills,{id,name,selected,amount:'',date:'',frequency:'monthly',subscription:/stream|gym/i.test(id)}]});}
 async function persist(next:SetupDraft){setBusy(true);setError('');try{const r=await fetch('/api/setup',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({draft:next,revision:draftRevision})});const result=await r.json() as {revision:number;error?:string};if(!r.ok)throw new Error(result.error);setDraftRevision(result.revision);setDraft(next);setSaved('Progress saved.');return true;}catch(e){setError(e instanceof Error?e.message:'Could not save progress.');return false;}finally{setBusy(false)}}
 const housingBill=draft.bills.find(b=>b.id==='setup-housing'||/rent|mortgage/i.test(b.name));
 function housing(choice:SetupDraft['housing']){const name=choice==='rent'?'Rent':'Mortgage',id=housingBill?.id??'setup-housing';const bill:SetupBill=housingBill?{...housingBill,name,selected:choice!=='neither'}:{id,name,selected:choice!=='neither',amount:'',date:'',frequency:'monthly',subscription:false};update({housing:choice,bills:housingBill?draft.bills.map(b=>b.id===id?bill:b):choice==='neither'?draft.bills:[...draft.bills,bill]});}
 let preview:ReturnType<typeof summarize>|null=null,reviewError='';if(step===6)try{preview=summarize(completeSetup(initialState,draft));}catch(e){reviewError=e instanceof Error?e.message:'Review your entries.';}
 type Card={key:string;title:string;hint:string;body:React.ReactNode;check?:()=>void};const cards:Card[]=[];
 const card=(key:string,title:string,hint:string,body:React.ReactNode,check?:()=>void)=>cards.push({key,title,hint,body,check});
 if(step===0){
 card('name','First, what should we call you?','Let’s make a plan that feels like yours.',<Field label="Your name" value={draft.name} onChange={name=>update({name})}/>,()=>{if(!draft.name.trim())throw new Error('Please enter your name.');});
 card('cash',`Hi ${draft.name.split(' ')[0]||'there'}. Where are we starting?`,'Checking and cash you can spend. Leave separate savings out.',<Field label="Money available right now ($)" type="number" min={0} step="0.01" value={draft.cash} onChange={cash=>update({cash})}/>,()=>{parseAmount(draft.cash,'available balance')});
 card('buffer','Keep a little peace of mind.','What amount would you like to leave untouched? $0 is okay.',<><Field label="Protected cash buffer ($)" type="number" min={0} step="0.01" value={draft.minimum} onChange={minimum=>update({minimum})}/><p className="field-help">This money stays in your account, but Carry keeps it out of your spending room.</p></>,()=>{parseAmount(draft.minimum,'cash buffer')});
 }
 if(step===1){
 card('work','What does work look like for you?','Whatever your situation, we can start from here.',<div className="slide-choices">{[{value:'employed',label:'Employed'},{value:'self-employed',label:'Self-employed / freelance'},{value:'student',label:'Student'},{value:'retired',label:'Retired'},{value:'between-jobs',label:'Between jobs'},{value:'other',label:'Other / prefer not to say'}].map(x=><button type="button" key={x.value} aria-pressed={draft.employment===x.value} className={draft.employment===x.value?'selected':''} onClick={()=>update({employment:x.value as SetupDraft['employment']})}>{x.label}{draft.employment===x.value&&<Check size={18}/>}</button>)}</div>);
 draft.income.forEach(i=>{
 card(i.id+'identity','Where does your income come from?','An employer, freelance work, benefits, or regular support.',<><Field label="Income source name" value={i.name} onChange={name=>editIncome({...i,name})}/><Field label="Employer or source · optional" required={false} value={i.employer} onChange={employer=>editIncome({...i,employer})}/><button type="button" className="text-action" onClick={()=>update({income:draft.income.filter(x=>x.id!==i.id)})}>Remove this source</button></>,()=>{if(!i.name.trim())throw new Error('Give this source a name.');});
 card(i.id+'pay',`Let’s map out ${i.name.toLowerCase()}.`,'Use your take-home amount after tax. Your best estimate is enough.',<><Field label="Estimated take-home amount ($)" type="number" min={.01} step="0.01" value={i.amount} onChange={amount=>editIncome({...i,amount})}/><Choice label="How often do you get paid?" value={i.frequency} onChange={frequency=>editIncome({...i,frequency:frequency as Frequency})} options={frequencies}/></>,()=>{parseAmount(i.amount,'take-home pay',false)});
 card(i.id+'date','When is the next one coming?','Already received it? Include it in your starting cash and choose the next payday.',<>{i.frequency==='semimonthly'&&<div className="form-grid">{[0,1].map(index=><Choice key={index} label={index===0?'First pay day':'Second pay day'} value={String(i.payDays[index])} onChange={v=>editIncome({...i,payDays:i.payDays.map((x,j)=>j===index?Number(v):x)})} options={Array.from({length:31},(_,n)=>({value:String(n+1),label:n===30?'Last day of month':String(n+1)}))}/>)}</div>}<Field label="Next expected payday" type="date" min={date} value={i.date} onChange={date=>editIncome({...i,date})}/></>,()=>validateStep({...draft,income:[i]},1,date));
 });
 card('add-income',draft.income.length?'Any other income to include?':'Let’s add your expected income.',draft.income.length?'Another job or regular support can be part of your plan.':'No regular income right now? You can continue without it.',<><div className="slide-tally"><BriefcaseBusiness size={24}/><strong>{draft.income.length} income {draft.income.length===1?'source':'sources'}</strong></div><button type="button" className="secondary wide" onClick={()=>update({income:[...draft.income,{id:uid(),name:'Paycheck',employer:'',amount:'',date:'',frequency:'biweekly',payDays:[1,15]}]})}><Plus size={18}/>Add an income source</button><p className="field-help">Estimates affect your forecast, never your current balance. We won’t contact your employer.</p></>);
 }
 if(step===2){
 card('housing','Let’s start with home.','Choose what applies to you.',<div className="housing-options">{[{value:'rent',label:'I rent',hint:'Apartment, house, or room'},{value:'mortgage',label:'I have a mortgage',hint:'Regular home loan payments'},{value:'neither',label:'Neither applies',hint:'No rent or mortgage to track'}].map(x=><button type="button" key={x.value} className={draft.housing===x.value?'selected':''} aria-pressed={draft.housing===x.value} onClick={()=>housing(x.value as SetupDraft['housing'])}><b>{x.label}</b><span>{x.hint}</span>{draft.housing===x.value&&<Check size={18}/>}</button>)}</div>,()=>{if(!draft.housing)throw new Error('Choose your housing situation.');});
 if(housingBill&&housingBill.selected)card('housing-payment','What’s your share?','Only include the portion you pay.',<BillFields bill={housingBill} onChange={editBill}/>,()=>validateStep({...draft,bills:[housingBill]},2,date));
 }
 if(step===3){
 billGroups.forEach(group=>card(group.title,group.title,group.hint,<div className="slide-checks">{group.items.map(([id,name])=><label className="bill-choice" key={id}><Checkbox checked={draft.bills.find(b=>b.id===id)?.selected??false} onCheckedChange={v=>chooseBill(id,name,v===true)}/><span>{name}</span></label>)}<p className="field-help">Choose all that apply, or continue with none. We’ll ask for amounts next.</p></div>));
 const custom=draft.bills.filter(b=>b.id!==housingBill?.id&&!billGroups.some(g=>g.items.some(([id])=>id===b.id)));
 card('custom-bills','Anything else to keep track of?','Property taxes, support payments, or another regular commitment.',<>{custom.map(b=><label className="bill-choice" key={b.id}><Checkbox checked={b.selected} onCheckedChange={v=>editBill({...b,selected:v===true})}/>{b.name||'New bill'}</label>)}<button type="button" className="secondary wide" onClick={()=>update({bills:[...draft.bills,{id:uid(),name:'Other bill',amount:'',date:'',frequency:'monthly',subscription:false,selected:true}]})}><Plus size={18}/>Add another bill</button></>);
 draft.bills.filter(b=>b.selected&&b.id!==housingBill?.id).forEach(b=>card('bill-'+b.id,`Let’s cover ${b.name.toLowerCase()}.`,'Your usual payment is enough. You can update it whenever it changes.',<BillFields bill={b} onChange={editBill}/>,()=>validateStep({...draft,bills:[b]},3,date)));
 }
 if(step===4){
 draft.categories.forEach(c=>card('category-'+c.id,`Make room for ${c.name.toLowerCase()}.`,'How much feels right for the next 30 days? Enter $0 if you don’t spend here.',<><Field label={c.name+' budget ($)'} type="number" min={0} step="0.01" value={c.budget} onChange={budget=>update({categories:draft.categories.map(x=>x.id===c.id?{...x,budget}:x)})}/><p className="field-help">Keep the bills you already entered separate.</p></>,()=>{parseAmount(c.budget,c.name+' budget')}));
 card('add-goal','A little something for your future?','Optional. Even a small monthly contribution can be a start.',<><div className="slide-tally"><Flag size={24}/><strong>{draft.goals.length?`${draft.goals.length} savings ${draft.goals.length===1?'goal':'goals'}`:'Your goals can start here'}</strong></div>{draft.goals.map(g=><div className="breakdown-row" key={g.id}><span>{g.name}</span><button type="button" className="text-action" onClick={()=>update({goals:draft.goals.filter(x=>x.id!==g.id)})}>Remove</button></div>)}<button type="button" className="secondary wide" onClick={()=>update({goals:[...draft.goals,{id:uid(),name:'Emergency fund',target:'',saved:'0',contribution:'',date:addDays(date,7),targetDate:monthDate(date,12),icon:'☂'}]})}><Plus size={18}/>Add a savings goal</button></>);
 draft.goals.forEach(g=>{const edit=(patch:Partial<typeof g>)=>update({goals:draft.goals.map(x=>x.id===g.id?{...x,...patch}:x)});
 card('goal-'+g.id,'What are you working toward?','Already-saved money here is held outside your spending accounts.',<><Field label="Goal name" value={g.name} onChange={name=>edit({name})}/><Field label="Target amount ($)" type="number" min={.01} step="0.01" value={g.target} onChange={target=>edit({target})}/><Field label="Already saved separately ($)" type="number" min={0} step="0.01" value={g.saved} onChange={saved=>edit({saved})}/></>,()=>{if(!g.name.trim())throw new Error('Give your goal a name.');if(parseAmount(g.saved,'saved amount')>parseAmount(g.target,'target',false))throw new Error('Your target must be at least the amount already saved.');});
 card('goal-plan-'+g.id,'Small steps, on your schedule.',`Choose a contribution for ${g.name.toLowerCase()}.`,<><Field label="Monthly contribution ($)" type="number" min={0} step="0.01" value={g.contribution} onChange={contribution=>edit({contribution})}/><Field label="Next savings contribution" type="date" value={g.date} onChange={date=>edit({date})}/><Field label="Target date" type="date" value={g.targetDate} onChange={targetDate=>edit({targetDate})}/></>,()=>validateStep({...draft,categories:[],goals:[g]},4,date));
 });
 }
 if(step===5){
 card('pay-reminders','A heads-up before payday.','Your estimate, plus bills coming up next.',<ReminderFields section="payday" value={draft.reminders} onChange={reminders=>update({reminders})} info={delivery.info} error={delivery.error}/>);
 card('bill-reminders','Fewer due-date surprises.','Choose a little time to prepare for bills.',<ReminderFields section="bills" value={draft.reminders} onChange={reminders=>update({reminders})} info={delivery.info} error={delivery.error}/>);
 card('email-reminders','Where should we give you a nudge?','Email is optional. Reminders also appear inside Carry.',<ReminderFields section="email" value={draft.reminders} onChange={reminders=>update({reminders})} info={delivery.info} error={delivery.error}/>);
 }
 if(step===6)card('review','Look at what you’ve put together.','Your plan is ready to review. Expand any section to check the details.',<>{reviewError?<p className="error-message">{reviewError} Go back to the matching step to fix it.</p>:preview&&<><section className="setup-runway"><span className="eyebrow">YOUR FIRST RUNWAY ESTIMATE</span><strong>{preview.runway.days}{preview.runway.capped?'+':''}<small>days</small></strong><p>{preview.runway.capped?'Your estimated income and spending keep you above your buffer throughout our 180-day forecast. This is a forecast limit, not an exact end date.':'Based on your available money, expected income, and commitments.'}</p></section><ReviewSection title="Your starting point" edit={()=>jump(0)}><div className="breakdown-row"><span>Available cash</span><b>{money(preview.balance,2)}</b></div><div className="breakdown-row"><span>Protected buffer</span><b>{money(Number(draft.minimum)*100,2)}</b></div></ReviewSection><ReviewSection title="Estimated income" edit={()=>jump(1)}>{draft.income.length?draft.income.map(i=><div className="breakdown-row" key={i.id}><span>{i.name}<small>{i.employer?i.employer+' · ':''}{i.date} · {i.frequency}</small></span><b>~{money(Number(i.amount)*100,2)}</b></div>):<p className="subtle">No future income included.</p>}</ReviewSection><ReviewSection title="Bills we’ll track" edit={()=>jump(3)}>{draft.bills.filter(b=>b.selected).map(b=><div className="breakdown-row" key={b.id}><span>{b.name}<small>{b.date} · {b.frequency}</small></span><b>{money(Number(b.amount)*100,2)}</b></div>)}{!draft.bills.some(b=>b.selected)&&<p className="subtle">No recurring bills selected.</p>}</ReviewSection><ReviewSection title="Spending & savings" edit={()=>jump(4)}>{draft.categories.map(c=><div className="breakdown-row" key={c.id}><span>{c.name}</span><b>{money(Number(c.budget)*100)}</b></div>)}{draft.goals.map(g=><div className="breakdown-row" key={g.id}><span>{g.name}</span><b>{money(Number(g.contribution)*100)}/mo</b></div>)}</ReviewSection><ReviewSection title="Your reminders" edit={()=>jump(5)}><p className="subtle">Payday: {draft.reminders.paydayEnabled?`${draft.reminders.paydayDays} days before`:'off'}. Bills: {draft.reminders.billsEnabled?`${draft.reminders.billDays} days before`:'off'}.</p><p className="subtle">Email: {draft.reminders.emailEnabled?(delivery.info?.deliveryStatus==='ready'?'enabled after you finish setup':'preference saved; delivery awaiting setup'):'off'}.</p></ReviewSection><p className="field-help">Finishing creates your accounts, income estimates, bills, spending buckets, and goals together. No money is moved.</p></>}</>);
 const index=Math.min(draft.slide??0,Math.max(0,cards.length-1)),active=cards[index];
 useEffect(()=>{if((draft.slide??0)!==index)setDraft(d=>({...d,slide:index}));if(!loading){heading.current?.focus({preventScroll:true});heading.current?.scrollIntoView({block:'start',behavior:'instant'});}},[step,index,loading]);
 async function next(){try{active.check?.();setError('');if(index<cards.length-1){await persist({...draft,slide:index+1});return;}if(step<6){validateStep(step===2?{...draft,bills:housingBill?[housingBill]:[]}:draft,step,date);await persist({...draft,step:step+1,slide:0});return;}setBusy(true);const r=await fetch('/api/setup/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({draft,profileRevision})});const value=await r.json() as {state:FinanceState;revision:number;error?:string};if(!r.ok)throw new Error(value.error);onComplete(value);}catch(e){setError(e instanceof Error?e.message:'Could not finish setup.');}finally{setBusy(false)}}
 return <main className={'guided-setup slide-setup '+(embedded?'embedded':'')}><header className="setup-top"><span className="brand">carry.</span><span>ONE SMALL STEP AT A TIME</span>{onCancel&&<button className="text-action" onClick={onCancel}>Back to my budget</button>}</header><div className="setup-layout"><aside className="setup-steps"><p className="eyebrow">YOUR PLAN, COMING TOGETHER</p>{steps.map((s,i)=><div className={i===step?'current':i<step?'complete':''} key={s.label}><span>{i<step?<Check size={16}/>:i+1}</span><p>{s.label}</p></div>)}<p className="setup-privacy">Your estimates stay private. No bank connection or employer contact required.</p></aside><section className="setup-main"><div className="setup-progress"><span>{details.label}</span><span>{step+1} / 7</span></div><Progress value={(step+(index+1)/cards.length)/7*100}/>{loading?<p aria-busy="true">Loading your saved progress…</p>:loadFailed?<p role="alert">{error}</p>:<form onSubmit={e=>{e.preventDefault();void next()}}><div className="setup-slide" key={active.key}><div className="slide-milestone"><span className="slide-icon"><details.icon size={23}/></span><span>{['A fresh start','Income, understood','Home, covered','One less thing to remember','Room for what matters','A little help along the way','You did the groundwork'][step]}</span>{step===6&&<Smile size={20}/>}</div><div className="setup-heading"><h1 ref={heading} tabIndex={-1}>{active.title}</h1><p>{active.hint}</p></div><div className="slide-content">{active.body}</div></div>{(error||saved)&&<p role={error?'alert':'status'} className={error?'error-message':'setup-saved'}>{error||saved}</p>}<footer className="setup-actions">{(step>0||index>0)&&<button type="button" className="secondary back" disabled={busy} onClick={()=>index>0?update({slide:index-1}):update({step:step-1,slide:2000})}><ArrowLeft size={18}/>Back</button>}<button className="primary" disabled={busy||!!reviewError}>{busy?'Saving…':step===6?'Finish setup & see my plan':index===cards.length-1?'Next chapter':'Continue'}{step===6?<Check size={18}/>:<ArrowRight size={18}/>}</button></footer><div className="slide-footer"><span>{index+1} of {cards.length} in this chapter</span><button type="button" className="text-action" disabled={busy} onClick={()=>void persist({...draft,slide:index})}>Save & come back</button></div></form>}</section></div></main>;
}
function ReviewSection({title,edit,children}:{title:string;edit:()=>void;children:React.ReactNode}){return <details className="setup-review"><summary>{title}<span>View details</span></summary><div className="review-content">{children}<button className="text-action" type="button" onClick={edit}>Edit {title.toLowerCase()}</button></div></details>}
