'use client';
import {useState} from 'react';
type Mode='login'|'signup'|'forgot'|'reset'|'signout';
const copy={login:{title:'Welcome back.',description:'Sign in to your Gift account.',button:'Sign in'},signup:{title:'A fresh start for your money.',description:'Create your Gift account to start your budget.',button:'Create account'},forgot:{title:'Forgot your password?',description:'Enter your email and we’ll send you a reset link.',button:'Send reset link'},reset:{title:'Choose a new password.',description:'Use at least 8 characters to protect your account.',button:'Save password'},signout:{title:'Sign out of Gift?',description:'Your saved budget will be here when you return.',button:'Sign out'}};
export default function AuthForm({mode,next='/',initialMessage=''}:{mode:Mode;next?:string;initialMessage?:string}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(initialMessage),[done,setDone]=useState(false);
 const hasEmail=['login','signup','forgot'].includes(mode),hasPassword=['login','signup','reset'].includes(mode),confirm=mode==='signup'||mode==='reset';
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setError('');setMessage('');const data=new FormData(event.currentTarget);const password=String(data.get('password')??'');if(confirm&&password!==data.get('confirmPassword')){setError('The passwords do not match.');return;}setBusy(true);try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({action:mode,email:data.get('email'),password,confirmPassword:data.get('confirmPassword'),next})});const result=await r.json() as {error?:string;message?:string;redirect?:string};if(!r.ok)throw Error(result.error??'Please try again.');if(result.redirect){window.location.assign(result.redirect);return;}setMessage(result.message??'Done.');setDone(true);}catch(e){setError(e instanceof Error?e.message:'Could not connect. Please try again.');}setBusy(false);}
 return <main className="startup"><section className="auth-card"><a className="brand" href="/">Gift</a><h1>{copy[mode].title}</h1><p>{copy[mode].description}</p>{error&&<div className="auth-error" role="alert">{error}</div>}{message&&<div className="auth-message" role="status">{message}</div>}{!done&&<form onSubmit={submit} aria-busy={busy}><fieldset disabled={busy}>{hasEmail&&<label className="field">Email<input className="carry-input" name="email" type="email" autoComplete="email" required maxLength={254}/></label>}{hasPassword&&<label className="field">{mode==='reset'?'New password':'Password'}<input className="carry-input" name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} required minLength={mode==='login'?undefined:8} maxLength={128}/></label>}{confirm&&<label className="field">Confirm password<input className="carry-input" name="confirmPassword" type="password" autoComplete="new-password" required minLength={8} maxLength={128}/></label>}<button className="primary" type="submit">{busy?'Please wait…':copy[mode].button}</button></fieldset></form>}<nav className="auth-links" aria-label="Account options">{mode==='login'?<><a href={'/auth/signup?next='+encodeURIComponent(next)}>Create account</a><a href="/auth/forgot">Forgot password?</a></>:<a href="/auth/login">Back to sign in</a>}{mode==='signout'&&<a href="/">Keep me signed in</a>}</nav>{mode==='login'&&<p className="auth-import">Moving from the original app? After signing in, <a href="/import">import your exported budget</a>.</p>}</section></main>;
}
