import {getChatGPTUser} from '@/app/chatgpt-auth';
import {readProfile,saveProfile,eraseProfile} from '@/lib/store';
import {financeSchema} from '@/lib/validation';
export const dynamic='force-dynamic';
const result=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
function sameOrigin(r:Request){return r.headers.get('origin')===new URL(r.url).origin;}
export async function GET(){try{const user=await getChatGPTUser();if(!user)return result({error:'Sign in to load your budget.'},401);return result(await readProfile(user.userId));}catch{return result({error:'Your budget could not be loaded. Please retry.'},503);}}
export async function POST(request:Request){try{const user=await getChatGPTUser();if(!user)return result({error:'Sign in to save your budget.'},401);if(!sameOrigin(request))return result({error:'Invalid request origin.'},403);if(Number(request.headers.get('content-length')??0)>3000000)return result({error:'Budget is too large.'},413);const body=await request.json() as {state:unknown;revision:number};const parsed=financeSchema.safeParse(body.state);if(!parsed.success||!Number.isInteger(body.revision)||body.revision<0)return result({error:parsed.success?'Invalid revision.':parsed.error.issues[0].message},400);return result(await saveProfile(user.userId,parsed.data,body.revision,user.email));}catch(e){return result({error:e instanceof Error&&e.message==='CONFLICT'?'This budget changed in another window. Reload before saving.':'Your changes could not be saved. Please retry.'},e instanceof Error&&e.message==='CONFLICT'?409:503);}}
export async function DELETE(request:Request){try{const user=await getChatGPTUser();if(!user)return result({error:'Sign in first.'},401);if(!sameOrigin(request))return result({error:'Invalid request origin.'},403);await eraseProfile(user.userId);return result({ok:true});}catch{return result({error:'Could not delete your data. Please retry.'},503);}}
