'use client';
import {useEffect,useState} from 'react';
import {Mail,CalendarDays,ArrowRight} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {Choice} from '@/components/carry/shared';
import {reminderDefaults,remindersFor} from '@/services/notifications';
import type {FinanceState} from '@/types/finance';
export type DeliveryInfo={email:string;deliveryStatus:'needs_sender'|'needs_scheduler'|'ready'};
export function useDeliveryInfo(){const [info,setInfo]=useState<DeliveryInfo|null>(null);const [error,setError]=useState('');useEffect(()=>{fetch('/api/reminders').then(async r=>{const d=await r.json() as DeliveryInfo&{error?:string};if(!r.ok)throw new Error(d.error);setInfo(d)}).catch(()=>setError('Email delivery status is unavailable. Reminders are not confirmed active.'));},[]);return {info,error};}
export function ReminderFields({value,onChange,info,error,section}:{section?:'payday'|'bills'|'email';value:typeof reminderDefaults;onChange:(v:typeof reminderDefaults)=>void;info:DeliveryInfo|null;error?:string}){return <>{(!section||section==='payday')&&<><div className="reminder-option"><div><h3>Before payday</h3><p>Your estimated take-home pay and bills coming next.</p></div><Switch aria-label="Payday reminders" checked={value.paydayEnabled} onCheckedChange={v=>onChange({...value,paydayEnabled:v})}/></div>{value.paydayEnabled&&<Choice label="Remind me before payday" value={String(value.paydayDays)} onChange={v=>onChange({...value,paydayDays:Number(v)})} options={[0,1,2,3,5,7,14].map(n=>({value:String(n),label:n===0?'On payday':`${n} day${n===1?'':'s'} before`}))}/>}</>}{(!section||section==='bills')&&<><div className="reminder-option"><div><h3>Before bills are due</h3><p>A little time to prepare for each payment.</p></div><Switch aria-label="Bill reminders" checked={value.billsEnabled} onCheckedChange={v=>onChange({...value,billsEnabled:v})}/></div>{value.billsEnabled&&<Choice label="Remind me before bills" value={String(value.billDays)} onChange={v=>onChange({...value,billDays:Number(v)})} options={[0,1,2,3,5,7,14].map(n=>({value:String(n),label:n===0?'On the due date':`${n} day${n===1?'':'s'} before`}))}/>}</>}{(!section||section==='email')&&<><div className="reminder-option"><div><h3><Mail size={16}/> Email reminders</h3><p>{info?.email?`Send to your signed-in email: ${info.email}`:'Use the email on your signed-in account.'}</p></div><Switch aria-label="Email reminders" checked={value.emailEnabled} onCheckedChange={v=>onChange({...value,emailEnabled:v})}/></div><Choice label="Preferred email time · your timezone" value={String(value.sendHour)} onChange={v=>onChange({...value,sendHour:Number(v)})} options={Array.from({length:24},(_,h)=>({value:String(h),label:`${h%12||12}:00 ${h<12?'AM':'PM'}`}))}/><div className={'delivery-notice '+(info?.deliveryStatus==='ready'?'ready':'')}><strong>{info?.deliveryStatus==='ready'?(value.emailEnabled?'Email delivery is available':'Email reminders are off'):'Email delivery is not active yet'}</strong><p>{error||(info?.deliveryStatus==='ready'?'Your preferences take effect when you save.':info?.deliveryStatus==='needs_scheduler'?'Your preferences can be saved. Automatic delivery still needs the reminder scheduler connected.':'Your preferences can be saved. Carry still needs a verified email sender and reminder scheduler before any emails can be sent.')}</p><p>Reminders also appear in Carry. Expected income is never added to your balance until you confirm it arrived.</p></div></>}</>}
export default function ReminderSettings({state,save,saving}:{state:FinanceState;save:(s:FinanceState)=>Promise<boolean>;saving:boolean}){const [settings,setSettings]=useState(state.reminders??reminderDefaults);const {info,error}=useDeliveryInfo();const [saved,setSaved]=useState(false);const [saveError,setSaveError]=useState('');return <div className="sheet-body"><ReminderFields value={settings} onChange={v=>{setSettings(v);setSaved(false)}} info={info} error={error}/><button className="primary wide" disabled={saving} onClick={async()=>{const ok=await save({...state,reminders:settings});setSaved(ok);setSaveError(ok?'':'Could not save your preferences. Please retry.')}}>{saving?'Saving…':'Save reminder preferences'}<ArrowRight size={17}/></button>{saveError&&<p role="alert" className="error-message">{saveError}</p>}{saved&&<p role="status" className="subtle">Preferences saved. {info?.deliveryStatus!=='ready'?'Email delivery is still awaiting setup.':''}</p>}</div>}
