import type { FinanceState, Frequency, Income, Category, Goal } from '@/types/finance';
export const money=(cents:number, decimals=0)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:decimals,minimumFractionDigits:decimals}).format(cents/100);
export const iso=(d:Date)=>d.toISOString().slice(0,10);
export const today=(timezone?:string)=>{const d=new Date();if(timezone){const parts=new Intl.DateTimeFormat('en-US',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d);return `${parts.find(x=>x.type==='year')!.value}-${parts.find(x=>x.type==='month')!.value}-${parts.find(x=>x.type==='day')!.value}`;}return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export const addDays=(date:string,n:number)=>iso(new Date(Date.parse(date+'T12:00:00Z')+n*86400000));
export const daysBetween=(a:string,b:string)=>Math.round((Date.parse(b+'T12:00:00Z')-Date.parse(a+'T12:00:00Z'))/86400000);
export const monthDate=(date:string,n:number)=>{const d=new Date(date+'T12:00:00Z');const day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+n);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));return iso(d)};
export function occurs(item:{date:string;frequency:Frequency;payDays?:number[]},date:string){if(date<item.date)return false;const delta=daysBetween(item.date,date);if(delta===0)return true;if(item.frequency==='once')return false;if(item.frequency==='weekly')return delta%7===0;if(item.frequency==='biweekly')return delta%14===0;const a=new Date(item.date+'T12:00:00Z'),b=new Date(date+'T12:00:00Z');const months=(b.getUTCFullYear()-a.getUTCFullYear())*12+b.getUTCMonth()-a.getUTCMonth();if(item.frequency==='monthly')return monthDate(item.date,months)===date;if(item.frequency==='yearly')return months%12===0&&monthDate(item.date,months)===date;const last=new Date(Date.UTC(b.getUTCFullYear(),b.getUTCMonth()+1,0)).getUTCDate();return (item.payDays??[1,15]).some(n=>b.getUTCDate()===Math.min(n,last));}
export const balance=(s:FinanceState)=>s.accounts.reduce((sum,a)=>sum+a.balance,0);
export function nextIncome(s:FinanceState,date=today(s.timezone)){for(let i=0;i<=180;i++){const day=addDays(date,i);const entries=s.income.filter(x=>occurs(x,day)&&!x.receivedDates?.includes(day));if(entries.length)return {date:day,days:i,amount:entries.reduce((a,b)=>a+b.amount,0)};}return null;}
export function upcomingBills(s:FinanceState,date=today(s.timezone),horizon=30){const items=[];const earliest=s.bills.filter(b=>!b.paused).reduce((min,b)=>b.date<min?b.date:min,date);for(let i=Math.max(-3660,daysBetween(date,earliest));i<horizon;i++){const day=addDays(date,i);for(const bill of s.bills)if(!bill.paused&&occurs(bill,day)&&!bill.paidDates.includes(day))items.push({...bill,due:day,days:i});}return items;}
export function categorySpent(s:FinanceState,id:string,start=s.periodStart,end=s.periodEnd){return s.transactions.filter(t=>!t.excluded&&t.date>=start&&t.date<=end).reduce((a,t)=>a+(t.splits?t.splits.filter(x=>x.categoryId===id).reduce((p,x)=>p+x.amount,0):t.categoryId===id?t.amount:0),0);}
export function calculateCategoryPace(s:FinanceState,c:Category,date=today(s.timezone)){const spent=categorySpent(s,c.id);const remaining=Math.max(0,c.budget-spent);const days=Math.max(1,daysBetween(date,s.periodEnd)+1);const total=Math.max(1,daysBetween(s.periodStart,s.periodEnd)+1);const elapsed=Math.max(1,total-days);const ratio=c.budget?spent/c.budget:1;return {spent,remaining,daily:Math.floor(remaining/days),ratio,status:ratio>=1?'EXHAUSTED':ratio>=.9?'ALMOST GONE':spent>c.budget*elapsed/total*1.15?'RUNNING HOT':spent<c.budget*elapsed/total*.8?'UNDER BUDGET':'ON TRACK'};}
export function expectedDailySpending(s:FinanceState){return Math.round(s.categories.reduce((a,c)=>a+c.budget,0)/Math.max(1,daysBetween(s.periodStart,s.periodEnd)+1));}
export function forecastBalance(s:FinanceState,date=today(s.timezone),horizon=180){let cash=balance(s);const rows=[];const goalRemaining=new Map(s.goals.map(g=>[g.id,Math.max(0,g.target-g.saved)]));for(let i=0;i<horizon;i++){const day=addDays(date,i);const openingBalance=cash;const income=s.income.filter(x=>occurs(x,day)&&!x.receivedDates?.includes(day)).reduce((a,b)=>a+b.amount,0);const bills=s.bills.filter(x=>!x.paused&&occurs(x,day)&&!x.paidDates.includes(day)).reduce((a,b)=>a+b.amount,0)+(i===0?upcomingBills(s,date,0).reduce((a,b)=>a+b.amount,0):0);const goals=s.goals.filter(x=>occurs({date:x.date,frequency:'monthly'},day)).reduce((a,g)=>{const amount=Math.min(g.contribution,goalRemaining.get(g.id)??0);goalRemaining.set(g.id,(goalRemaining.get(g.id)??0)-amount);return a+amount;},0);const spending=expectedDailySpending(s);const purchases=s.purchases.filter(x=>x.date===day).reduce((a,b)=>a+b.amount,0);cash+=income-bills-goals-spending-purchases;rows.push({date:day,day:i,openingBalance,income,bills,goals,spending,purchases,balance:cash});}return rows;}
export function calculateRunway(s:FinanceState,date=today(s.timezone)){if(balance(s)<=s.protectedMinimum)return {days:0,capped:false};const rows=forecastBalance(s,date);const end=rows.find(x=>x.balance<=s.protectedMinimum);return {days:end?.day??180,capped:!end};}
export const calculateBillReserve=(s:FinanceState,date=today(s.timezone),days=30)=>upcomingBills(s,date,days).reduce((a,b)=>a+b.amount,0);
export const calculateGoalReserve=(s:FinanceState,date=today(s.timezone),days=30)=>forecastBalance(s,date,days).reduce((a,b)=>a+b.goals,0);
export function calculateFreeToSpend(s:FinanceState,date=today(s.timezone)){const days=Math.max(1,nextIncome(s,date)?.days??Math.max(1,daysBetween(date,s.periodEnd)+1));return Math.max(0,balance(s)-s.protectedMinimum-calculateBillReserve(s,date,days)-calculateGoalReserve(s,date,days)-s.purchases.filter(x=>x.date>=date&&x.date<addDays(date,days)).reduce((a,b)=>a+b.amount,0));}
export function calculateSafeToSpend(s:FinanceState,date=today(s.timezone)){const days=Math.max(1,nextIncome(s,date)?.days??daysBetween(date,s.periodEnd)+1);const free=calculateFreeToSpend(s,date);const remaining=s.categories.reduce((a,c)=>a+calculateCategoryPace(s,c,date).remaining,0);const spentToday=s.transactions.filter(x=>x.date===date&&!x.excluded).reduce((a,b)=>a+b.amount,0);const allowance=Math.min(free,remaining);const daily=Math.floor((allowance+spentToday)/days);return {today:daily,spentToday,remaining:Math.max(0,daily-spentToday),weekend:Math.min(allowance,daily*2),untilPayday:allowance,days};}
export function calculateGoalCompletion(g:Goal,date=today()){if(g.saved>=g.target)return {months:0,date};if(g.contribution<=0)return {months:null,date:null};const months=Math.ceil((g.target-g.saved)/g.contribution);return {months,date:monthDate(g.date,months-1)};}
export function simulatePurchase(s:FinanceState,amount:number,date=today(s.timezone),purchaseDate=date){
 const adjusted={...s,purchases:[...s.purchases,{id:'scenario',name:'Purchase scenario',amount,date:purchaseDate}]};
 const beforeRows=forecastBalance(s,date),afterRows=forecastBalance(adjusted,date);
 const offset=daysBetween(date,purchaseDate),withinForecast=offset>=0&&offset<180;
 const beforeCash=withinForecast?beforeRows[offset].balance:null,afterCash=withinForecast?afterRows[offset].balance:null;
 const lowestBefore=Math.min(balance(s),...beforeRows.map(r=>r.balance))-s.protectedMinimum;
 const lowestAfter=Math.min(balance(s),...afterRows.map(r=>r.balance))-s.protectedMinimum;
 return {before:calculateRunway(s,date),after:calculateRunway(adjusted,date),safeBefore:calculateSafeToSpend(s,date).remaining,safeAfter:calculateSafeToSpend(adjusted,date).remaining,billsCovered:afterRows.slice(0,Math.max(1,nextIncome(s,date)?.days??30)).every(x=>x.balance>=s.protectedMinimum),beforeCash,afterCash,lowestBefore,lowestAfter,withinForecast,purchaseDate};
}
export const simulateIncomeChange=(s:FinanceState,id:string,amount:number,date=today(s.timezone))=>calculateRunway({...s,income:s.income.map(x=>x.id===id?{...x,amount}:x)},date);
export const simulateExpenseChange=(s:FinanceState,id:string,amount:number,date=today(s.timezone))=>calculateRunway({...s,bills:s.bills.map(x=>x.id===id?{...x,amount}:x)},date);
export function summarize(s:FinanceState,date=today(s.timezone)){const runway=calculateRunway(s,date),safe=calculateSafeToSpend(s,date),bills=upcomingBills(s,date),payday=nextIncome(s,date);return {date,balance:balance(s),runway,safe,bills,payday,billReserve:calculateBillReserve(s,date),goalReserve:calculateGoalReserve(s,date),free:calculateFreeToSpend(s,date),daily:expectedDailySpending(s),forecast:forecastBalance(s,date,30),categories:s.categories.map(c=>({...c,...calculateCategoryPace(s,c,date)}))};}
export function parseBill(text:string,date=today()){const amount=text.match(/\$\s*([\d,]+(?:\.\d{1,2})?)/);const number=text.match(/(?:on|around|the)\s+(?:the\s+)?(\d{1,2})(?:st|nd|rd|th)?\b/i);const word=text.match(/\b(first|second|third)\b/i);if(!amount||(!number&&!word))throw new Error('Include an amount and due day, like “Rent is $1,200 on the 1st every month.”');const day=number?Number(number[1]):['first','second','third'].indexOf(word![1].toLowerCase())+1;if(day<1||day>31)throw new Error('Choose a due day from 1 to 31.');let due=date.slice(0,8)+String(Math.min(day,new Date(Date.UTC(Number(date.slice(0,4)),Number(date.slice(5,7)),0)).getUTCDate())).padStart(2,'0');if(due<date)due=monthDate(due,1);const name=text.slice(0,amount.index).replace(/^my\s+/i,'').replace(/\s+(is|costs)\s*$/i,'').trim();if(!name)throw new Error('Include a bill name.');return {name:name[0].toUpperCase()+name.slice(1),amount:Math.round(Number(amount[1].replaceAll(',',''))*100),date:due,frequency:'monthly' as Frequency};}
export function advisorAnswer(s:FinanceState,question:string,date=today(s.timezone)){const q=question.toLowerCase(),m=summarize(s,date);const amount=Number(q.match(/\$?([\d,]+(?:\.\d+)?)/)?.[1]?.replaceAll(',','')??200)*100;if(/afford|spend|buy|purchase|weekend/.test(q)){const sim=simulatePurchase(s,amount,date);return `A ${money(amount)} purchase would leave ${sim.after.days}${sim.after.capped?'+':''} days of runway, compared with ${sim.before.days}${sim.before.capped?'+':''} today. Bills before your next payday ${sim.billsCovered?'remain covered':'may not all be covered'}. Your remaining safe spending today changes from ${money(sim.safeBefore)} to ${money(sim.safeAfter)}.`;}if(/rent|bill.*increase/.test(q)){const rent=s.bills.find(x=>/rent/i.test(x.name));return rent?`Adding ${money(amount)} to ${rent.name} would put your runway at ${simulateExpenseChange(s,rent.id,rent.amount+amount,date).days} days. This is a scenario only; your bill has not changed.`:'Add a rent bill first to model this change.';}if(/bill|due|week/.test(q)){const list=upcomingBills(s,date,7);return list.length?`Due in the next seven days: ${list.map(x=>`${x.name}, ${money(x.amount)} on ${x.due}`).join('; ')}. Total: ${money(list.reduce((a,b)=>a+b.amount,0))}.`:'No tracked bills are due in the next seven days.';}if(/save|goal/.test(q)){return s.goals.length?s.goals.map(g=>`${g.name}: ${money(g.target-g.saved)} left. At ${money(g.contribution)}/month, ${calculateGoalCompletion(g,date).date?'estimated completion is '+calculateGoalCompletion(g,date).date:'set a contribution to get a completion estimate'}.`).join('\n'):'Add your first savings goal to calculate a contribution plan.';}if(/down|drop|decrease|why/.test(q)){const prior=s.snapshots.filter(x=>x.date<date).at(-1);return prior?`Your last saved runway was ${prior.runway} days on ${prior.date}; today it is ${m.runway.days}. Your planned daily spending is ${money(m.daily,2)}. A snapshot comparison alone does not establish the cause.`:'There isn’t an earlier daily snapshot yet. Gift will save one each day so you can compare your runway over time.';}return `You have ${money(m.balance)} in available accounts and ${m.runway.days}${m.runway.capped?'+':''} days of projected runway. ${m.categories.filter(c=>c.status==='RUNNING HOT'||c.status==='ALMOST GONE'||c.status==='EXHAUSTED').map(c=>`${c.name} has ${money(c.remaining)} left in its budget.`).join(' ')||'Your categories are within their planned pace.'} You can ask about bills, goals, spending, or a purchase.`;}
