'use client';
import {useCallback,useEffect,useState} from 'react';
import type {FinanceState} from '@/types/finance';
import {emptyState} from '@/services/finance/sample';
import {summarize,today} from '@/services/finance';
export function useFinance(){const [state,setState]=useState<FinanceState>(()=>emptyState());const [demo,setDemo]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [offline,setOffline]=useState(false);const [revision,setRevision]=useState(0);const [notice,setNotice]=useState('');const [loaded,setLoaded]=useState(false);const [currentDay,setCurrentDay]=useState(()=>today());
useEffect(()=>{const tick=()=>setCurrentDay(today(state.timezone));tick();const timer=window.setInterval(tick,30000);window.addEventListener('focus',tick);document.addEventListener('visibilitychange',tick);return()=>{window.clearInterval(timer);window.removeEventListener('focus',tick);document.removeEventListener('visibilitychange',tick)}},[state.timezone]);
const reload=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/finance',{cache:'no-store'}),json=await r.json() as {error:string;state:FinanceState;revision:number};if(!r.ok)throw new Error(json.error);setRevision(json.revision);setState({...json.state,timezone:json.state.onboarded?(json.state.timezone??Intl.DateTimeFormat().resolvedOptions().timeZone):Intl.DateTimeFormat().resolvedOptions().timeZone});setDemo(false);setLoaded(true);setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to load your budget.');}finally{setLoading(false)}},[]);
useEffect(()=>{void reload();const update=()=>setOffline(!navigator.onLine);update();window.addEventListener('online',update);window.addEventListener('offline',update);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update)}},[reload]);
async function save(next:FinanceState,force=false){setError('');if(offline){setError('You’re offline. Reconnect to save your changes.');return false;}if(demo&&!force){setState(next);setNotice('Sample updated. Your real budget hasn’t changed.');return true;}setSaving(true);try{const r=await fetch('/api/finance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:next,revision})});const json=await r.json() as {error:string;state:FinanceState;revision:number};if(!r.ok)throw new Error(json.error);setState(json.state);setRevision(json.revision);setDemo(false);setNotice('Saved to your private budget.');return true;}catch(e){setError(e instanceof Error?e.message:'Unable to save.');return false;}finally{setSaving(false)}}
useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(t)},[notice]);
useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>void}}).modelContext;if(!context)return;const controller=new AbortController();try{context.registerTool({name:'get_carry_summary',description:'Read the current visible Carry budget summary. Amounts are integer cents; sample indicates demonstration data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(input&&typeof input==='object'&&Object.keys(input).length)throw new Error('No parameters expected');return {sample:demo,...summarize(state,today())}}},{signal:controller.signal})}catch{}return()=>controller.abort()},[state,demo]);
function accept(result:{state:FinanceState;revision:number}){setState(result.state);setRevision(result.revision);setDemo(false);setLoaded(true);setError('');setNotice('Your plan is ready. Welcome to Carry.');}
return {accept,revision,loaded,state,data:summarize(state,currentDay),demo,loading,saving,error,offline,notice,save,reload,setError,setState,setDemo,setRevision};}
