import {getChatGPTUser} from '@/app/chatgpt-auth';
import {supabaseAdmin} from '@/lib/supabase/server';
import {subscriptionRequired} from '@/lib/billing/access';
const bucket='gift-memories';
const valid=(id:string)=>/^[a-f0-9-]{36}\.jpg$/.test(id);
export async function GET(r:Request){const user=await getChatGPTUser();if(!user)return new Response(null,{status:401});const id=new URL(r.url).searchParams.get('id')??'';if(!valid(id))return new Response(null,{status:400});const {data,error}=await supabaseAdmin().storage.from(bucket).download(`${user.userId}/${id}`);if(error||!data)return new Response(null,{status:404});return new Response(data,{headers:{'Content-Type':'image/jpeg','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
export async function POST(r:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in first.'},{status:401});if(r.headers.get('origin')!==new URL(r.url).origin)return new Response(null,{status:403});const denied=await subscriptionRequired(user.userId,user.email);if(denied)return denied;
 try{if(r.headers.get('content-type')!=='image/jpeg'||Number(r.headers.get('content-length')??0)>2000000)return Response.json({error:'Choose a JPEG smaller than 2 MB.'},{status:400});const bytes=await r.arrayBuffer();const magic=new Uint8Array(bytes);if(bytes.byteLength>2000000||magic[0]!==255||magic[1]!==216||magic[2]!==255)return new Response(null,{status:400});const storage=supabaseAdmin().storage.from(bucket);const listed=await storage.list(user.userId,{limit:201});if(listed.error)throw listed.error;if((listed.data?.length??0)>=200)return Response.json({error:'Your photo library is full (200 photos). Remove a saved photo before adding more.'},{status:409});const id=crypto.randomUUID()+'.jpg';const {error}=await storage.upload(`${user.userId}/${id}`,bytes,{contentType:'image/jpeg',upsert:false});if(error)throw error;return Response.json({id});}catch{return Response.json({error:'Photo storage is unavailable. Your budget has not changed.'},{status:503});}}
export async function DELETE(r:Request){const user=await getChatGPTUser();if(!user)return new Response(null,{status:401});if(r.headers.get('origin')!==new URL(r.url).origin)return new Response(null,{status:403});const id=new URL(r.url).searchParams.get('id')??'';if(!valid(id))return new Response(null,{status:400});const {error}=await supabaseAdmin().storage.from(bucket).remove([`${user.userId}/${id}`]);return Response.json({ok:!error},{status:error?503:200});}
